language: objective-c 

# macOS and Xcode Version
osx_image: xcode10

# Build dependencies
install:
  - brew install python3
  - pip3 install virtualenv
  - virtualenv -p python3 .
  - ./fetchDependencies -v

# Cache built deps
cache:
  directories:
    - External

script:
  - xcodebuild -project MoltenVKPackaging.xcodeproj -scheme "MoltenVK Package"
  - xcodebuild -workspace Demos/Demos.xcworkspace -scheme "Cube-macOS"

