language: objective-c 

# macOS and Xcode Version
# Xcode 9.4 running on macOS 10.13
osx_image: xcode9.4

# Build dependencies
install:
  - brew install python3
  - ./fetchDependencies

# Cache built deps
cache:
  directories:
    - External

script:
  - xcodebuild -scheme "MoltenVK Package (Release)"
  - xcodebuild -workspace Demos/Demos.xcworkspace -scheme "Cube-macOS"

